name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      matrix: # matrix é uma estratégia de teste paralelo que permite executar o mesmo job (tarefa) em múltiplas configurações diferentes automaticamente.
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm test

      - name: Upload cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload mochawesome report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: mochawesome-report
          retention-days: 30
